### ISSUE TITLE
driver-did-web does not start

### ISSUE THREAD

**Issue by astanciu** [decentralized-identity/universal-registrar#60]
Trying to run the env as described in the readme, getting this error in the driver-did-web container

```
driver-did-web_1     | java.lang.IllegalArgumentException: Base path is not a directory!
driver-did-web_1     | 	at uniregistrar.driver.did.web.DidWebDriver.<init>(DidWebDriver.java:56)
driver-did-web_1     | 	at uniregistrar.driver.did.web.DidWebDriver.<init>(DidWebDriver.java:43)
```

**Comment by cihanss** [comment]
Hi @astanciu, I assume you have the issue because the given 'uniregistrar_driver_did_web_basePath` does not exist in the container, and no volume is mounted for that path (by default). The documentation and/or Docker configuration needs to be updated. I have noted the issue.

**Comment by cihanss** [comment]
Hi @astanciu, I assume you have the issue because the given `uniregistrar_driver_did_web_basePath` does not exist in the container, and no volume is mounted for that path (by default). The documentation and/or Docker configuration needs to be updated. I have noted the issue.

**Comment by astanciu** [comment]
Even if I set the env var to just `/opt` which definitely exists, it still throws the same error... (unless something else is going on there, maybe permissions). I will try mapping a volume

**Comment by cihanss** [comment]
`/opt` should give: `java.lang.IllegalArgumentException: Base path is not writable!` since container starts with user **jetty** . Please ensure environment variables are passed to docker-compose correctly. Meanwhile, I have updated the [uni-registrar-driver-did-web](https://github.com/decentralized-identity/uni-registrar-driver-did-web) to solve some of the confusion around configuration, thanks to your feedback.

**Comment by astanciu** [comment]
Thank you, was able to start it by building the docker image locally first. Maybe something's wrong with the image pushed to dockerhub.
